name: Build and Release to AMO
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Install and Build 🔧
        run: |
          npm install
          npm run build

      - name: Release to AMO 🚀
        run: |
          npm install web-ext-submit
          cd dist/firestore-manager/webextension
          web-ext-submit
        env:
          WEB_EXT_API_KEY: ${{ secrets.WEB_EXT_API_KEY }}
          WEB_EXT_API_SECRET: ${{ secrets.WEB_EXT_API_SECRET }}
